# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.PositiveIntegerField(blank=True)),
                ('image', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.FloatField(default=0.0)),
                ('total_tracks', models.PositiveIntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'modified')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('card_image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=b'', verbose_name=b'Card Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Artist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_taggedgenre_items', to='api.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='api.TaggedGenre', to='api.Genre', verbose_name=b'Genre'),
        ),
    ]
