# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.PositiveIntegerField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.SmallIntegerField(blank=True)),
                ('explicit_content', models.BooleanField()),
                ('popularity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='card_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=b'media', verbose_name=b'Card Image'),
        ),
    ]
